version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Java 17
      - java -version

  build:
    commands:
      - echo Build started on `date`
      # 构建 Lambda 子模块
      - cd lambda
      - mvn clean package -DskipTests
      - cd ..
      # 构建主项目
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
    - lambda/target/*.jar